### PR TITLE
 Update secrethub-go to v0.21.0

### PR DESCRIPTION
**Pull request by SimonBarendse**

### CODE REVIEW

**Comment by florisvdg** [comment]
What's the thought behind this?

**Comment by SimonBarendse** [comment]
@florisvdg `secrethub-go` `v0.21` adds support for AWS services, for which I'd like to add a resource. 

Furthermore, these changes are also required to upgrade to a `v0.21+` version, e.g. to get the changes to directories that are currently in the pipeline: https://github.com/secrethub/secrethub-go/pull/124 , which are required for a directory resource, which I'd like to add as well.

And, last but not least, it lays the ground work for adding native AWS authentication, which is added in `v0.21`. We still have to add a way to activate this though. I propose to do this by reading the `SECRETHUB_AUTH_PROVIDER` envvar in the client when no auth provider option is configured (this will require another update of the Go client) and we might want to add an option to configure this on the provider itself.

**Comment by florisvdg** [comment]
Yes, I get that the Go client needs to be updated, but what about the other stuff in the PR?

**Comment by SimonBarendse** [comment]
@florisvdg `v0.21` included some breaking changes to client initialization. Changes to use the new initialization mechanism are included in the PR.

Furthermore, applications are now encouraged to identify themselves, which is done by setting the app info (`terraform-provider-secrethub` in this case). This enables us to see what applications are being used and on which versions, to provide better support and help with debugging.

The last change is made to fetch dependencies via the go proxy. One of Terraform's dependencies is hosted on git.apache.org, [which has been down for a couple of days now](https://status.apache.org/). By using the proxy, we circumvent ever hitting that host.

If you prefer, I can split these changes up in separate PRs.

**Pull request merged**
